### ISSUE TITLE
EmuDeck Stuck on 'Finishing Update'

### ISSUE THREAD

**Issue by ryankazokas** [EmuDeck/emudeck-we#29]
It looks like it has the incorrect path in the link

https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck-Setup-2.2.0.exe.blockmap

vs

https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck.Setup.2.2.1.exe.blockmap

The . vs the - after EmuDeck is the difference. 

```
[2023-12-23 15:34:39.724] [info]  Download block maps (old: "https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck-Setup-2.2.0.exe.blockmap", new: https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck-Setup-2.2.1.exe.blockmap)
[2023-12-23 15:34:39.829] [error] Cannot download differentially, fallback to full download: Error: Cannot download "https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck-Setup-2.2.0.exe.blockmap", status 404: 
    at ClientRequest.<anonymous> (C:\Users\user1\AppData\Local\Programs\EmuDeck\resources\app.asar\dist\main\main.js:2:97343)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49128)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
[2023-12-23 15:34:40.517] [error] Error: Error: Cannot download "https://github.com/EmuDeck/emudeck-electron/releases/download/v2.1.4/EmuDeck-Setup-2.2.1.exe", status 404: 
    at ClientRequest.<anonymous> (C:\Users\user1\AppData\Local\Programs\EmuDeck\resources\app.asar\dist\main\main.js:2:97343)
    at ClientRequest.emit (node:events:513:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49128)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
```

Is there a folder i can put this in manually to by pass the http download? or is there a way to change the path it should pull from?

**Comment by ryankazokas** [comment]
Or maybe this is just a naming convention in the release?
